 name: gitartwork from a contribution graph
 on: 
   push:
   schedule:
     - cron: '* */24 * * *'
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
         with:
            # Use this username's contribution graph  
            user_name: gauravkanwat
            # Text on contribution graph 
            text: GAURAV
       - uses: jasineri/simple-push-action@v1
